### ISSUE TITLE
Error Compilation error: startup failed. Unable to resolve various classes. 

### ISSUE THREAD

**Issue by mobilars** [silverbullet-dk/opentele-server#2]
I'm getting some build errors like the following. Is this due to the bootstrap-data? There don't seem to be any of these files in my project path. I'm not Groovy-fluent so I may be doing something wrong. 

/home/LarsXDS/opentele/opentele-server/grails-app/conf/BootStrap.groovy: 38: unable to resolve class org.opentele.server.model.questionnaire.QuestionnaireGroup
 @ line 38, column 1.
   import org.opentele.server.model.questionnaire.QuestionnaireGroup
   ^

/home/LarsXDS/opentele/opentele-server/grails-app/conf/BootStrap.groovy: 34: unable to resolve class org.opentele.server.model.cgm.MealEvent
 @ line 34, column 1.
   import org.opentele.server.model.cgm.MealEvent
   ^

/home/LarsXDS/opentele/opentele-server/grails-app/conf/BootStrap.groovy: 40: unable to resolve class org.opentele.server.model.questionnaire.StandardSchedule
 @ line 40, column 1.
   import org.opentele.server.model.questionnaire.StandardSchedule
   ^

/home/LarsXDS/opentele/opentele-server/grails-app/conf/BootStrap.groovy: 18: unable to resolve class org.opentele.server.core.model.types.Weekday
 @ line 18, column 1.
   import org.opentele.server.core.model.types.Weekday

**Comment by ErikMejerHansen** [comment]
You need to check out the the https://github.com/silverbullet-dk/opentele-server-core-plugin repo in a folder adjacent to where you checked out the  OpenTele server project. 

(And I need to update the Readme to reflect that).

**Comment by mobilars** [comment]
Cool. That fixed that one. Very close now. Next, while starting:

2015-04-24 11:24:42,276 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Object of class [org.opentele.server.model.Patient] with identifier [1]: optimiic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.opentele.server.model.Patient#
org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException: Object of class [org.opentele.server.model.Patient] with identifier [1]: optimistic locking failed; nested exception is org.hiberte.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.opentele.server.model.Patient#1]
        at BootStrap$_addStandardThresholds2Patient_closure21_closure38.doCall(BootStrap.groovy:1729)
        at BootStrap$_addStandardThresholds2Patient_closure21.doCall(BootStrap.groovy:1726)
        at BootStrap.addStandardThresholds2Patient(BootStrap.groovy:1723)

**Comment by ErikMejerHansen** [comment]
That onde looks more serious. Could you provide all of the log?

**Comment by mobilars** [comment]
Here's the standard log. I guess I could turn up debugging level. I have
not set up any db, so I'm just assuming (perhaps wrongly) that it's using
H2 and it needs to setup. If that's not the case, I'm sorry :-/ and if you
let me know how to set up, I'll try it.

| Compiling 7 source files.....
Using database url: jdbc:h2:clinicianDb;MVCC=TRUE;IGNORECASE=TRUE
Using database url: jdbc:h2:clinicianDb;MVCC=TRUE;IGNORECASE=TRUE
| Running Grails application
Using database url: jdbc:h2:clinicianDb;MVCC=TRUE;IGNORECASE=TRUE
Using database url: jdbc:h2:clinicianDb;MVCC=TRUE;IGNORECASE=TRUE

Configuring Spring Security Core ...
... finished configuring Spring Security Core
2015-04-24 11:24:26,325 [localhost-startStop-1] DEBUG conf.BootStrap  -
Adding messaging to service
Initializing for core DEVEL
2015-04-24 11:24:35,625 [localhost-startStop-1] DEBUG core.PasswordService
- Loading words for temp passwords....
  2015-04-24 11:24:35,680 [localhost-startStop-1] DEBUG core.PasswordService
- ... 2540 words loaded.
  Initializing for DEVEL
  2015-04-24 11:24:36,109 [quartzScheduler_Worker-1] DEBUG
  server.QuestionnaireScheduleCheckJob  - Checking for blue alarms..
  2015-04-24 11:24:41,658 [quartzScheduler_Worker-1] DEBUG
  server.QuestionnaireScheduleCheckJob  - New blue alarms for Linda Hansen:
  [34, 36, 41]
  2015-04-24 11:24:42,276 [localhost-startStop-1] ERROR
  context.GrailsContextLoaderListener  - Error initializing the application:
  Object of class [org.opentele.server.model.Patient] with identifier [1]:
  optimiic locking failed; nested exception is
  org.hibernate.StaleObjectStateException: Row was updated or deleted by
  another transaction (or unsaved-value mapping was incorrect) :
  [org.opentele.server.model.Patient#
  org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException:
  Object of class [org.opentele.server.model.Patient] with identifier [1]:
  optimistic locking failed; nested exception is
  org.hiberte.StaleObjectStateException: Row was updated or deleted by
  another transaction (or unsaved-value mapping was incorrect) :
  [org.opentele.server.model.Patient#1]
      at
  BootStrap$_addStandardThresholds2Patient_closure21_closure38.doCall(BootStrap.groovy:1729)
      at
  BootStrap$_addStandardThresholds2Patient_closure21.doCall(BootStrap.groovy:1726)
      at BootStrap.addStandardThresholds2Patient(BootStrap.groovy:1723)
      at BootStrap.createTestPatients(BootStrap.groovy:622)
      at BootStrap.doBootstrapForTest(BootStrap.groovy:273)
      at
  BootStrap$_closure1_closure33_closure34.doCall(BootStrap.groovy:174)
      at
  grails.util.Environment$EnvironmentBlockEvaluator.execute(Environment.java:340)
      at
  grails.util.Environment.executeForEnvironment(Environment.java:321)
      at
  grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
      at java.util.concurrent.FutureTask.run(FutureTask.java:262)
      at
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      at
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
      at java.lang.Thread.run(Thread.java:745)
  Caused by: org.hibernate.StaleObjectStateException: Row was updated or
  deleted by another transaction (or unsaved-value mapping was incorrect) :
  [org.opentele.server.model.Patient#1]
      ... 13 more
  2015-04-24 11:24:42,327 [quartzScheduler_Worker-1] ERROR
  spi.SqlExceptionHelper  - Database is already closed (to disable automatic
  closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL)
  [90121-6]
  2015-04-24 11:24:42,366 [quartzScheduler_Worker-1] ERROR
  server.QuestionnaireScheduleCheckJob  - Got exception when updating blue
  alarms for 11.
  org.springframework.dao.DataAccessResourceFailureException: Hibernate
  operation: could not prepare statement; SQL [select numericthr0_.id as
  id1_56_0_, numericthr0_1_.version as version2_56_0_,
  numericthr0_1_reated_by as created_3_56_0_, numericthr0_1_.created_date as
  created_4_56_0_, numericthr0_1_.modified_by as modified5_56_0_,
  numericthr0_1_.modified_date as modified6_56_0_, numericthr0_1_.type_id as
  type_id76_0_, numericthr0_.alert_high as alert_hi2_27_0_,
  numericthr0_.alert_low as alert_lo3_27_0_, numericthr0_.warning_high as
  warning_4_27_0_, numericthr0_.warning_low as warning_5_27_0_ from
  numeric_threshold nuricthr0_ inner join threshold numericthr0_1_ on
  numericthr0_.id=numericthr0_1_.id where numericthr0_.id=?]; Database is
  already closed (to disable automatic closing at VM shutdown, add
  ";DB_CLOSE_ON_EXIT=FALS to the db URL) [90121-176]; nested exception is
  org.h2.jdbc.JdbcSQLException: Database is already closed (to disable
  automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db
  URL) [90121-176]
      at
  opentele.server.QuestionnaireScheduleCheckJob$_execute_closure1_closure3.doCall(QuestionnaireScheduleCheckJob.groovy:34)
      at
  org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:815)
      at
  org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:715)
      at
  opentele.server.QuestionnaireScheduleCheckJob$_execute_closure1.doCall(QuestionnaireScheduleCheckJob.groovy:31)
      at
  opentele.server.QuestionnaireScheduleCheckJob.execute(QuestionnaireScheduleCheckJob.groovy:30)
      at
  grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:104)
      at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
      at
  org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
  Caused by: org.h2.jdbc.JdbcSQLException: Database is already closed (to
  disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to
  the db URL) [90121-176]
      at
  org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
      at org.h2.message.DbException.get(DbException.java:178)
      at org.h2.message.DbException.get(DbException.java:154)
      at org.h2.message.DbException.get(DbException.java:143)
      at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1468)
      at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1443)
      at org.h2.jdbc.JdbcConnection.getAutoCommit(JdbcConnection.java:446)
      at
  io.jdev.miniprofiler.sql.log4jdbc.ConnectionSpy.prepareStatement(ConnectionSpy.java:389)
      ... 8 more
  2015-04-24 11:24:42,494 [quartzScheduler_Worker-1] ERROR
  listeners.ExceptionPrinterJobListener  - Exception occurred in job: Grails
  Job
  org.quartz.JobExecutionException:
  org.springframework.transaction.TransactionSystemException: Could not roll
  back Hibernate transaction; nested exception is
  org.hibernate.TransactionException: rollback failedSee nested exception:
  org.springframework.transaction.TransactionSystemException: Could not roll
  back Hibernate transaction; nested exception is
  org.hibernate.TransactionException: rollback failed]
      at
  grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:111)
      at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
      at
  org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
  Caused by: org.springframework.transaction.TransactionSystemException:
  Could not roll back Hibernate transaction; nested exception is
  org.hibernate.TransactionException: rollback failed
      at
  org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:815)
      at
  org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:715)
      at
  opentele.server.QuestionnaireScheduleCheckJob$_execute_closure1.doCall(QuestionnaireScheduleCheckJob.groovy:31)
      at
  opentele.server.QuestionnaireScheduleCheckJob.execute(QuestionnaireScheduleCheckJob.groovy:30)
      at
  grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:104)
      ... 2 more
  Caused by: org.hibernate.TransactionException: rollback failed
      ... 7 more
  Caused by: org.hibernate.TransactionException: unable to rollback against
  JDBC connection
      ... 7 more
  Caused by: org.h2.jdbc.JdbcSQLException: Database is already closed (to
  disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to
  the db URL) [90121-176]
      at
  org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
      at org.h2.message.DbException.get(DbException.java:178)
      at org.h2.message.DbException.get(DbException.java:154)
      at org.h2.message.DbException.get(DbException.java:143)
      at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1468)
      at
  org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1453)
      at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:486)
      at
  io.jdev.miniprofiler.sql.log4jdbc.ConnectionSpy.rollback(ConnectionSpy.java:881)
      ... 7 more

2015-04-24 13:29 GMT+02:00 Erik Mejer Hansen notifications@github.com:

> That onde looks more serious. Could you provide all of the log?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/silverbullet-dk/opentele-server/issues/2#issuecomment-95904506
> .

## 

Lars Kristian Roland
Email: lars@roland.bz
Phone: +47 90733036

**Comment by ErikMejerHansen** [comment]
You're quite right. It will default to filebased H2. 
You might try and delete cliniciandb-file and starting the grails app again. 
Meanwhile I'll try to figure out whats causing the issue.

**Comment by mobilars** [comment]
Tried deleting file. Restarted. same error.

2015-04-24 13:52 GMT+02:00 Erik Mejer Hansen notifications@github.com:

> You're quite right. It will default to filebased H2.
> You might try and delete cliniciandb-file and starting the grails app
> again.
> Meanwhile I'll try to figure out whats causing the issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/silverbullet-dk/opentele-server/issues/2#issuecomment-95908224
> .

## 

Lars Kristian Roland
Email: lars@roland.bz
Phone: +47 90733036

**Comment by mobilars** [comment]
When I comment out this section, it compiles and start. I get an other
optimistic locking failed errror, but the server starts, and I can log in.
Thanks.

def addStandardThresholds2Patient(Patient p) {
        p.refresh() /*
        //Add standard thresholds
        p.patient2PatientGroups.each { p2pg ->
            //If more than one PG for the patient, the thresholds will be
overwritten, since we
            //currently do not support a set of thresholds per patientGroup
per patient
            p2pg.patientGroup.standardThresholdSet.thresholds.each {

```
            Threshold t = it.duplicate()
            t.save(failOnError: true, flush: true)
            p.setThreshold(t)
        }
    }
```

*/
        p.save(failOnError: true, flush: true)
    }

2015-04-24 14:00 GMT+02:00 Lars Kristian Roland lars@roland.bz:

> Tried deleting file. Restarted. same error.
> 
> 2015-04-24 13:52 GMT+02:00 Erik Mejer Hansen notifications@github.com:
> 
> > You're quite right. It will default to filebased H2.
> > You might try and delete cliniciandb-file and starting the grails app
> > again.
> > Meanwhile I'll try to figure out whats causing the issue.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/silverbullet-dk/opentele-server/issues/2#issuecomment-95908224
> > .
> 
> ## 
> 
> Lars Kristian Roland
> Email: lars@roland.bz
> Phone: +47 90733036

## 

Lars Kristian Roland
Email: lars@roland.bz
Phone: +47 90733036
